### ISSUE TITLE
[feat] 내서재 화면 구현

### ISSUE THREAD

**Issue by skylartosf** [SOPT-31th-App2-Kyobo-Electronic-Libary/Kyobo-AOS#12]
## ISSUE
- fragment_my_page.xml 뷰 짜기

## To-Do
- [ ] 상단에 [홍익대학교] 부분 - 수민이의 홈화면 참고
- [ ]  [회원 정보 + 아이콘] 부분
- [ ] 대출 목록 실제로 나오는 부분 = RecyclerView
