### ISSUE TITLE
[ui, feat] 메인 페이지 뷰 수정

### ISSUE THREAD

**Issue by wateralsie** [SOPT-31th-App2-Kyobo-Electronic-Libary/Kyobo-AOS#20]
## ISSUE
- 메인 페이지 뷰 수정

## To-Do
- [x] 대출, 신규, 카테고리 아이템 간 간격 주기
- [x] 베스트 도서 아이템 description 글자 길이 제한주기
- [x] 전체 아이템 이미지 다시 조정하기
- [x] ScrollView 추가하기
- [ ] 즐겨찾기 버튼 구현하기
- [x] 베스트도서 RecyclerView 그리드로 설정하기
